//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BycicleShop.Common.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public Basket()
        {
            this.ProductsCounts = new HashSet<ProductsCount>();
        }
    
        public int BasketId { get; set; }
        public int UserId { get; set; }
        public bool Active { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ProductsCount> ProductsCounts { get; set; }
    }
}
