//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BycicleShop.Common.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductsCounts = new HashSet<ProductsCount>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string Adress { get; set; }
        public bool Received { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PhoneNumber { get; set; }
        public string Review { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ProductsCount> ProductsCounts { get; set; }
    }
}
