//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BycicleShop.Common.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string Adress { get; set; }
        public Nullable<bool> Obtained { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<int> ProductOrderId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ObtainedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ProductOrder ProductOrder { get; set; }
        public virtual User User { get; set; }
    }
}
